### ISSUE TITLE
search page

### ISSUE THREAD

**Issue by tmastrangelo** [CSNSE/csn-twitter#19]
search button in navbar -> search page -> filters through users, tweets, and hashtags (later)?

**Comment by tymastrangelo** [comment]
search feature works, checks for results every time a character is entered or deleted. the results show up as tweets based off of the characters entered in the search bar at any given moment. results filter most recent at the top.

this is a great start for the search functionality.

**Comment by tymastrangelo** [comment]
future

- when tweet is clicked from search, user should be able to swipe back to search page and not to home page. 
- should edit tweet component to not have likes and all other buttons on the search results.
- separate search sections between users, names, and tweet content.
